MODELS_PATH: "./harmonization_exps/models"
EXPS_PATH: "./harmonization_exps"

HFLICKR_PATH: "path/to/HFlickr"
HDAY2NIGHT_PATH: "path/to/Hday2night"
HCOCO_PATH: "path/to/HCOCO"
HADOBE5K_PATH: "path/to/HAdobe5k_resized1024"
HADOBE5K_RS_PATH: "path/to/HAdobe5k"
HADOBE5K_2048_PATH: "path/to/HAdobe5k_resized2048_2048"
HADOBE5K_1024_PATH: "path/to/HAdobe5k_resized1024_1024"
